
spring:
  config:
    activate:
      on-profile: common
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 1800000
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  config: classpath:logback.xml

---

spring:
  profiles:
    active: local
    default: local
    group:
      local: local
      test: test, common
      dev:  dev, common
      prod: prod, common

---

## 로컬

spring:
  config:
    activate:
      on-profile: local, test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

server:
  port: 8080

---

## 개발

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:


---

## 운영

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

server:
  port: 274832


