spring:
  config:
    activate:
      on-profile: common
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: true
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      mode: always


jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  config: classpath:logback.xml

decorator:
  datasource:
    p6spy:
      multiline: false

security:
  jwt:
    token:
      secret-key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      expire-length: 30

---

spring:
  profiles:
    active: local
    default: local
    group:
      local: local, common
      test: test, common
      dev: dev, common
      prod: prod, common

---

## 로컬

spring:
  config:
    activate:
      on-profile: local, test
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

---

## 개발

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driver-class-name: org.mariadb.jdbc.Driver

---

## 운영

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 274832