INSERT INTO ADVENTURER
VALUES (2L, 'GENERAL', 'user1@gmail.com',
        '$2a$10$yxmlE1fKRduWxvTqrThx4OByZeY9ZUxdTRoloNn262TkcfAbotyke', 'NONE');
INSERT INTO ADVENTURE_AUTHORITY
VALUES (2L, 1L, 'ROLE_USER');