drop table if exists adventure_authority cascade;
drop table if exists adventurer cascade ;
create table adventure_authority (adventure_id bigint not null, id bigint not null, role varchar(255), primary key (id));
create table adventurer (id bigint generated by default as identity, account_type varchar(255) check (account_type in ('GENERAL','SNS')), email varchar(255), password varchar(255), sns_type varchar(255) check (sns_type in ('KAKAO','DISCORD','NONE')), primary key (id));
alter table if exists adventure_authority add constraint FKisxw49c2xljxc07eynchc1qv7 foreign key (adventure_id) references adventurer;
